Append Operator to LinearAdvectionLaxFriedrichs, Concatenation and ComponentProjection
pymor/pymor pull request #1046
Opened 2020-08-06 07:26 UTC by pmli

Closes #989.

2020-08-17 14:25 UTC, pmli commented
> Maybe it would be nice to have functions `Concatenation` etc. which are marked with `@deprecated` for the next release.

Agreed. Does it look ok?

2020-08-17 15:07 UTC, renefritze commented
Should we maybe start to a running list of deprecations in the release notes? Would make writing them a bit simlper.

2020-08-17 16:00 UTC, pmli commented
> Should we maybe start to a running list of deprecations in the release notes? Would make writing them a bit simlper.

Sounds good to me. I've added a remark to the release notes.

2020-08-17 16:11 UTC, sdrave commented
> > Should we maybe start to a running list of deprecations in the release notes? Would make writing them a bit simlper.
> 
> Sounds good to me. I've added a remark to the release notes.

Can't we just grep for `@deprecated`?

2020-08-26 11:00 UTC, sdrave requested changes

2020-08-26 11:00 UTC, sdrave commented on src/pymor/basic.py
> +                                           VectorOperator, VectorFunctional, FixedParameterOperator, AdjointOperator,
I think, we should also add the deprecated versions for now, to ensure user code that imports from `basic` does not break.

2020-08-26 15:47 UTC, sdrave approved these changes

2020-08-27 08:34 UTC, merged