Prevent corruption of memory cache
pymor/pymor pull request #1136
Opened 2020-10-27 14:30 UTC by sdrave

This PR changes the behavior of `MemoryRegion` to always make a `deepcopy` of any values stored in the cache and to only return deep copies of the values contained in the cache. While this may increase the memory footprint and somewhat hurt performance, it seems like the only way to make using `MemoryRegion` really safe. The practical impact of the increased memory usage should be quite small, IMHO.

Note that the current provisions of returning copies of `VectorArrays` and making NumPy arrays immutable had no effect since all values stored in the cache are actually 2-tuples.

See #1133 for a non-obvious real world example of `MemoryRegion` being corrupted.

2020-10-27 14:54 UTC, renefritze requested changes
Could we try to trim down @ftalbrecht's example code that exhibited the error and add it as a test case?

2020-10-27 15:15 UTC, sdrave commented
@renefritze, the Enforce PR labels thing is failing again. We had similar issues some time ago. Maybe we should disable it?

2020-10-27 16:17 UTC, renefritze approved these changes

2020-10-27 16:20 UTC, renefritze commented
> @renefritze, the Enforce PR labels thing is failing again. We had similar issues some time ago. Maybe we should disable it?

Lets see if the update fixing the run first

2020-10-28 12:44 UTC, ftalbrecht approved these changes
I have no better suggestion than deep copy, looks good.

2020-10-28 13:25 UTC, merged