Implementation dmd
pymor/pymor pull request #1267
Opened 2021-03-10 14:25 UTC by hvhue

First implemetation of Dynamic Mode Decomposition and some simple tests using the parabolic and heat demos

2021-03-10 14:31 UTC, TiKeil commented
Hi @hvhue, you should rebase your branch on main such that the CI can start.

2021-03-11 14:34 UTC, renefritze commented
The gitlab documentation build failures are due to missing references. That's not straight-forward to see in the log. 
https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/547837#L5496

2021-03-12 15:46 UTC, TiKeil commented
Now the failures in the docs build comes can be found here
https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/549064#L4166, 
i.e. you should seprate authors with "and" and not with a comma :), see
https://tex.stackexchange.com/questions/343163/error-in-bib-entry-too-many-commas

2021-03-19 16:52 UTC, sdrave requested changes
Hi @hvhue, thanks for your pull request! I added several minor comments. 

Regarding the demo scripts: Can you try to merge the test scripts and use typer for cli argument parsing as it is done in `parabolic.py`? I didn't check what `parabolicDMD_test` does compared to the other two scripts, but generally I would say that one script is enough. We should discuss at some point what a good testcase for dmd would be. We can still change the concrete example later on, however. 

Apart from the demo scripts it would also be great if we also had a short [tutorial](https://docs.pymor.org/2020.2.0/tutorials.html) which also very briefly explains the main mathematical ideas behind the method.

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +    See Algorithm 3.1 in [EMKB19]_.
```suggestion
    See Algorithm 3.1 in :cite:`EMKB19`.
```

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +    See Algorithm 4.1 in [EMKB19]_.
```suggestion
    See Algorithm 4.1 in :cite:`EMKB19`.
```

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +    randomisierte QB-Zerlegung
```suggestion
    Randomized QB decomposition.
```

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +        The |VectorArray| for which the randomized QB Decomposition is to be computed.
```suggestion
        The |VectorArray| for which the randomized QB decomposition is to be computed.
```

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +        The desired rank for the decomposition. If None rank = len(A).
```suggestion
        The desired rank for the decomposition. If `None`, rank = len(A).
```

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +        Distribution used for the random projectionmatrix Omega. (`'normal'` or `'uniform'`)
```suggestion
        Distribution used for the random sample matrix (`'normal'` or `'uniform'`).
```

(The name 'omega' was not defined in the docstring so we should not use it ..

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +        Oversamplingparameter. Number of extra columns of the projectionmatrix.
```suggestion
        Oversampling parameter. Number of extra columns of the sample matrix.
```

Is the term 'projection matrix' used in the literature? If any of the matrices, I would call 'Q' the projection matrix, not omega.

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +def rand_QB(A, target_rank=None, distribution='normal', oversampling=0, powerIterations=0):
Camel case violates PEP8. (Surprisingly, the linter did not seem to catch that.) Please use `power_iterations` instead.

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +        Number of power Iterations.
```suggestion
        Number of power iterations.
```

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +        |VectorArray| containig an approximate optimal Basis for the Image of the Inputmatrix A.
```suggestion
        |VectorArray| containig an approximate basis for the image of the input matrix A.
```

Not sure what optimal would mean in that context. Any basis for the image would work equally well.

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +        Numpy Array. Projection of the Input Matrix into the lower dimensional subspace.
```suggestion
        Numpy array. Projection of the input matrix into the lower dimensional subspace.
```

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +        The |VectorArray| for which the DMD Modes are to be computed.
```suggestion
        The |VectorArray| for which the DMD modes are to be computed.
```

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +        Number of DMD Modes to be computed. If None target_rank = len(A).
```suggestion
        Number of DMD modes to be computed. If `None` target_rank = len(A).
```

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +        Distribution used for the randomized QB-Decomposition. (`'normal'` or `'uniform'`)
```suggestion
        Distribution used for the randomized QB-Decomposition (`'normal'` or `'uniform'`).
```

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +        Oversamplingparameter. Number of extra columns of the projectionmatrix.
```suggestion
        Oversampling parameter. Number of extra columns of the sample matrix.
```
See above.

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +             oversampling=0, powerIterations=0, order=True):
See above regarding `powerIterations`.

2021-03-19 16:52 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +        Numpy Array containig time scaled eigenvalues: `ln(l)/dt`.
```suggestion
        Numpy array containig time scaled eigenvalues: `ln(l)/dt`.
```

2021-03-19 16:52 UTC, sdrave commented on src/pymordemos/parabolicDMD_TEST.py
> +# m.visualize(U, title='Solution of Parabolic Problem')
```suggestion
```

2021-03-19 16:52 UTC, sdrave commented on src/pymordemos/parabolicDMD_TEST.py
> +alle_fehler_dmd = []
Please use only English identifiers ..

2021-03-19 16:52 UTC, sdrave commented on src/pymordemos/parabolicDMD_TEST.py
> +# Testmoden = [1, 20, 50, 80]
```suggestion
```

2021-03-19 16:52 UTC, sdrave commented on src/pymordemos/parabolicDMD_TEST.py
> +# Testmoden = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
```suggestion
```

2021-03-24 09:28 UTC, renefritze requested changes
It would be great if you can add the demo script into the test suite, too. That is fairly straightforward to do by adding a new tuple of arguments [here](https://github.com/pymor/pymor/blob/main/src/pymortests/demos.py#L122) (first string is the demo name, rest demo args) and then adding that tuple to `DEMO_ARGS`.

2021-04-23 15:55 UTC, sdrave requested changes
Hi @hvhue, this is looking much better already! Some more comments:

- Both demo scripts seem to do exactly the same, except for applying dmd to different FOMs. Maybe you can merge the two scripts into one?
- In `algorithms.randrangefinder`, there are already randomized algorithms to determine the range of an `Operator`. Maybe you could merge your code with the existing algorithms?
- You should add an entry to `AUTHORS.md`!

2021-04-23 15:55 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +
In pyMOR, we don't have blank lines between arguments. Could you remove them?

2021-04-23 15:55 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +
```suggestion
```

2021-04-23 15:55 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +
```suggestion
```

2021-04-23 15:55 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +    Sigma_inv = np.linalg.inv(SVALS_diag)
```suggestion
    Sigma_inv = np.diag(1/SVALS)
```

2021-04-23 15:55 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +    # Solve the least Sqaures Problem
```suggestion
    # Solve the least Squares Problem
```

2021-04-23 15:55 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +    # omega = np.log(EVALS) / dt
Why is this here?

2021-04-23 15:55 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +    print('SVD of XL...')
Can you replace all print statements in the library code by corresponding logging code like, for instance, in `pymor.algorithms.gram_schmidt.gram_schmidt`?

2021-04-23 15:55 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +    Ramdomized QB decomposition
```suggestion
    """Ramdomized QB decomposition.
```

2021-04-23 15:55 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +    '''Compute amplitueds b using least-squares: Fb=x1'''
```suggestion
    """Compute amplitueds b using least-squares: Fb=x1"""
```

2021-04-23 15:55 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +    '''Compute Vandermonde matrix'''
```suggestion
    """Compute Vandermonde matrix"""
```

2021-04-23 15:55 UTC, sdrave commented on src/pymordemos/burgers_dmd.py
> +"""
```suggestion
"""Burgers demo with different Applications of Dynamic Mode Decomposition."""
```

2021-04-23 15:55 UTC, sdrave commented on src/pymor/algorithms/dmd.py
> +    Y = A.lincomb(Omega)[:target_rank]
This doesn't look quite right! With the slicing you just throw away all additional vectors you get from oversampling!? I think there is actually an issue with the original paper. Maybe you should look at this point more closely and also take a look at what is done in HMT11. We can also discuss this further in more detail if you wish.

2021-04-23 15:56 UTC, sdrave commented
I forgot: You also need to rebase on main to get CI working again.

2022-04-05 13:24 UTC, renefritze commented
This was superseded by #1424 and can be closed, right @pymor/main ?

2023-11-23 10:47 UTC, sdrave commented
I'm closing this now, as the PR is quite old now and of it is in #1424. The randomized part could be easily reimplemented and should use `pymor.algorithms.rand_la`.

2023-11-23 10:47 UTC, closed without merging