Add methods to `models.iosys` for exporting matrices
pymor/pymor pull request #1309
Opened 2021-05-17 14:06 UTC by pmli

This PR adds `to_*` methods to `LTIModel` and `SecondOrderModel`, tests for `from_*` and `to_*` methods, and output methods to `tools.io`. The tests should cover most of what is not covered by #1300 in `models.iosys`. I'm not how the CI will react to creating temporary files; I guess we'll see.

2021-05-17 14:21 UTC, renefritze approved these changes

2021-05-23 19:14 UTC, lbalicki approved these changes

2021-05-27 11:09 UTC, sdrave requested changes
LGTM. However, could you remove the type annotations for now? I don't think it is quite clear at the moment if/when we will have type annotations in pyMOR ..

2021-05-31 06:36 UTC, pmli commented
> LGTM. However, could you remove the type annotations for now? I don't think it is quite clear at the moment if/when we will have type annotations in pyMOR ..

I removed the type annotations now.

I also realized that probably `save_matrix` should be tested as much as `load_matrix` is. Currently, files in `pymortests/data/matrices` are used to test `load_matrix`. How about removing those and testing `save_matrix` and `load_matrix` by a round trip as for `iosys` models?

2021-05-31 06:49 UTC, renefritze commented
I like the current setup as it forces one to consider backwards compat. Maybe we could use the saved (or a new set, since that'll be easier) compare files also for a check if `save` reproduces them?

2021-06-04 12:33 UTC, sdrave approved these changes

2021-06-04 13:05 UTC, merged