update mailmap and add CI check
pymor/pymor pull request #1497
Opened 2021-12-14 11:52 UTC by renefritze

Compared to #1491 this drops adding mailmap updates from release checklist,
and adds a gitlab CI check instead.

2021-12-14 13:25 UTC, pmli commented
Can this detect when both the name and email change (as with Josefine)?

2021-12-14 13:42 UTC, renefritze commented
> Can this detect when both the name and email change (as with Josefine)?

Hmm, no. It also doesn't catch "same email - different names". Which is easy enough to add. But for Josefine's case it's harder to detect. Would need some fuzzier matching of the name I guess, which I have very little experience with.

2021-12-16 09:29 UTC, renefritze commented
I think this can now be merged instead of #1491, @pmli

2021-12-17 15:06 UTC, pmli requested changes

2021-12-17 15:06 UTC, pmli commented on .mailmap
> +Jonas Nicodemus <jonas.nicodemus@icloud.com> <44996273+Jonas-Nicodemus@users.noreply.github.com>
It would be good to sort this alphabetically.

2021-12-17 15:06 UTC, pmli commented on docs/RELEASE_CHECKLIST.md
> + 1. [ ] All developers check if for mailmap correctness.
```suggestion
 1. [ ] All developers check for mailmap correctness.
```

2021-12-17 15:47 UTC, renefritze commented
Thanks @pmli! All fixed now.

2021-12-17 21:53 UTC, pmli approved these changes

2021-12-17 21:53 UTC, merged