Improve MPI related interpreter shutdown issues
pymor/pymor pull request #1540
Opened 2022-01-19 12:33 UTC by sdrave

- In `mpi_wrap_model` ensure proper cleanup of objects managed by pyMOR's MPI event loop.
- Issue a warning when there are still managed objects when the event loop is shut down.
- Switch import order for petsc4py and mpi4py.

The last commit locally fixes petsc trying to communicate after MPI_Finalize during interpreter shutdown. @renefritze, was there any reason for the prior import oder?

2022-01-19 12:44 UTC, renefritze commented
> The last commit locally fixes petsc trying to communicate after MPI_Finalize during interpreter shutdown. @renefritze, was there any reason for the prior import oder?

Yes. Petsc4py was (in petsc) calling `MPI_Init`, which prevents the setup code from working. 
Did you try making mpi4py not call finalize instead? Via [`PYMOR_MPI_FINALIZE`](https://docs.pymor.org/2021-2-0/environment.html)

2022-01-19 13:19 UTC, sdrave commented
> > The last commit locally fixes petsc trying to communicate after MPI_Finalize during interpreter shutdown. @renefritze, was there any reason for the prior import oder?
> 
> Yes. Petsc4py was (in petsc) calling `MPI_Init`, which prevents the setup code from working. Did you try making mpi4py not call finalize instead? Via [`PYMOR_MPI_FINALIZE`](https://docs.pymor.org/2021-2-0/environment.html)

Turns out I was apparently confused about the initial situation: With main I get complaints about finalize not being called. Then I added manual calls to finalize, which apparently were too early. So, at least in my situation `mpi4py.rc.finalize` is `None`, resulting pyMOR to set it to `False`, whereas the mpi4py's default behavior is to do call finalize.  At least in my case this needs to happen in order to get proper cleanup. Is there any good reason to default to `False` instead of `True`?

2022-01-19 13:26 UTC, renefritze commented
> Is there any good reason to default to `False` instead of `True`?

Yes. Last time I did that all checks where fenics was actually used segfaulted on interpreter shutdown.

2022-01-19 14:17 UTC, sdrave commented
> > Is there any good reason to default to `False` instead of `True`?
> 
> Yes. Last time I did that all checks where fenics was actually used segfaulted on interpreter shutdown.

Strange that it seems to be the other way around on my machine (although no segfault). I will check what will currently happen in CI when defaulting to `True` ..

2022-01-24 10:22 UTC, sdrave commented
@renefritze, 'from_source 3/3' consistently fails due to some 404. Has this already been fixed somewhere?

2022-01-24 10:29 UTC, renefritze commented
I haven't. What's the problem?

2022-01-24 14:15 UTC, sdrave commented
> I haven't. What's the problem?

https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/803081

2022-01-24 14:22 UTC, renefritze commented
I don't know anything about that.

2022-01-24 15:03 UTC, sdrave commented
> I don't know anything about that.

Then this seems to be a new issue, not related to this PR I'd say.

2022-01-26 07:24 UTC, renefritze requested changes

2022-01-26 07:24 UTC, renefritze commented on src/pymor/__init__.py
> +    finalize = os.environ.get('PYMOR_MPI_FINALIZE', mpi4py.rc.finalize if mpi4py.rc.finalize is not None else True)
I think this change needs to be reflected in documentation

2022-01-26 13:20 UTC, renefritze approved these changes

2022-01-26 15:17 UTC, merged