GRSVD fixes
pymor/pymor pull request #1630
Opened 2022-05-16 18:41 UTC by artpelling

This PR will fix some typos in the docstring and logger of `random_generalized_svd`. I also had a read of the cited paper and I think the new docstring is easier to understand.

2022-05-24 20:45 UTC, sdrave requested changes

2022-05-24 20:45 UTC, sdrave commented on src/pymor/algorithms/rand_la.py
> +        \langle x, y \rangle_S = x^TSy
```suggestion
        (x, y)_S = x^TSy
```

This is the notation, I have used in the 'Building a Reduced Basis' tutorial, and I'd say it's also more standard in mathematics. Pointy brackets are for dual pairings ...

2022-05-24 20:45 UTC, sdrave commented on src/pymor/algorithms/rand_la.py
> +        \langle x, y \rangle_T = x^TTy.
```suggestion
        (x, y) = x^TTy.
```
see above.

2022-05-25 08:27 UTC, artpelling commented
Thanks! I had swapped the notation too many times :sweat_smile:

2022-06-07 11:26 UTC, sdrave approved these changes

2022-06-07 11:38 UTC, sdrave commented
@artpelling, I think you need to rebase on main to make ci pass.

2022-06-07 12:33 UTC, sdrave commented
This should also be changed in `adaptive_rrf` then. @pmli, do you see any reasons not to use the default tolerances?

2022-06-08 10:40 UTC, renefritze commented
The problem actually was that Github Actions aren't run for a commit (The conda env update) added from Github Actions. I've reordered the commits here with a rebase.

2022-06-09 07:00 UTC, sdrave commented
@artpelling, can you rebase again? Hopefull, ci should finally pass.

2022-06-09 07:40 UTC, renefritze commented
> @artpelling, can you rebase again?

Went ahead and did that

2022-06-09 11:29 UTC, sdrave commented
I think another rebase is necessary. The hypothesis fixes hadn't been merged yet.

2022-06-10 08:16 UTC, merged