Allow ParameterSpace to project parameters into its ranges
pymor/pymor pull request #1787
Opened 2022-10-27 14:01 UTC by peoe

The method implemented here will allow any `ParameterSpace` to project any given parameter of suitable dimensions into its respective parameter ranges. This feature will in particular come in handy when trying to implement optimization algorithms such as TR-RB because of the often imposed rectangular parameter bounds.

One small problem that needs to be addressed is the nomenclature of the method: usually `project` methods call upon generalizable `ProjectionRules` as these methods refer to the projection of operators, etc. onto subbases and the like. Here however no such behaviour is intended because of the simple use case (we only ever want to "project" a parameter when in use with a `ParameterSpace`). If you've got any better suggestions for naming the method, please let me know or amend it directly in the code.

2022-11-01 15:12 UTC, peoe commented
> This sound like clipping to me

Alright, I renamed `project` to `clip`, I wasn't aware of that numpy function.

2022-11-01 16:39 UTC, pmli commented on src/pymor/parameters/base.py
> +        The projected |parameter values|.
```suggestion
        The clipped |parameter values|.
```

2022-11-02 09:08 UTC, TiKeil commented on src/pymor/parameters/base.py
> +            for j in range(size):
it's probably more convenient to use `numpy.clip` here as well.

2022-11-10 16:29 UTC, sdrave requested changes
@peoe, can you rebase on current main? This should make CI failure go away, I believe.

Two more things I just became aware of:
1. Your implementation strips all values in `mu` which are not parameters of the space. Is this desired? (I'd tend to say yes.)
2. For time-dependent `mu`, the result is no longer time-dependent. (I'd think this is fine as well.)

@pmli, do you think differently?

2022-11-10 17:55 UTC, pmli commented
> Two more things I just became aware of:
> 
> 1. Your implementation strips all values in `mu` which are not parameters of the space. Is this desired? (I'd tend to say yes.)
> 2. For time-dependent `mu`, the result is no longer time-dependent. (I'd think this is fine as well.)
> 
> @pmli, do you think differently?

No, this seems fine to me too. I'm not even sure what would be the use case for clipping the input.

2022-11-11 15:57 UTC, peoe commented on src/pymor/parameters/base.py
> +        return Mu(((key, mu_dict[key]) for key in self.parameters))
You're right, this is much simpler!

2022-11-11 16:56 UTC, peoe commented
> @peoe, can you rebase on current main?

Will do! EDIT: seems like I messed that up, oops!

>     1. Your implementation strips all values in `mu` which are not parameters of the space. Is this desired? (I'd tend to say yes.)

I'm unsure which behaviour I'd expect in this cause to be honest. On one hand it might be more intuitive to assume `clip` strips values that aren't in the parameter space because of their missing ranges, on the other one might reason as to the preservation of unmentioned `mu` values.

One solution would be the following:
```python
def clip(self, mu, keep_additional=False):
    [...]
    clipped = {key: np.clip(mu[key], range_[0], range_[1]) for key, range_ in self.ranges.items()}
    if keep_additional:
        additional = {key: mu[key] for key in mu if key not in clipped}
        clipped = dict(clipped, **additional)
    return Mu(clipped)
```
This allows for the user to specify if they'd like to keep the additional values in `mu` while discarding them by default.

For now I'd suggest this implementation to offer flexibility. If there are better ways to solve this issue please let me know.

2022-11-17 16:15 UTC, sdrave requested changes
See my comments. 

However, as nobody really said that they would want/need the option to keep the additional parameter, I'm also fine with leaving the feature out. You decide ..

2022-11-18 16:29 UTC, sdrave requested changes

2022-11-23 11:35 UTC, sdrave commented on src/pymortests/parameters/parameters.py
> +    upper_mu = {k: space.ranges[k][1] for k in keys}
I don't think this is correct: `space.ranges[k][1]` is a single number, but you need an array of shape `(space.parameters[k],)`.  The test only works becaus `space` is a single space which happens to have only one parameter, which is one-dimensional.

While we are at it, you could try to parameterize the fixture. If you want to do that, let me know if you need any help with that.

Minor remark: You could just write `for k in self.parameters`.

2022-11-29 11:35 UTC, peoe commented
I've decided to add the fix from #1806 to this PR because the parametrized fixture depends on it. This PR now closes #1805.

2022-12-05 09:40 UTC, HenKlei commented
Hi @peoe, thanks for the PR, to me this looks very good. I was just wondering if you want to add the small clarification to the documentation you had in #1806? If so, you could simply cherry-pick [a926590](https://github.com/pymor/pymor/pull/1806/commits/a9265908caed6bec5b12df482e982bc50444fa02) and replace [e1d2ebd](https://github.com/pymor/pymor/pull/1787/commits/e1d2ebd138ccce0f8a2c216b645ae39f5cbf9a1e) by that commit. Further, to make the CI pass again, you can rebase on main.

2022-12-06 07:57 UTC, HenKlei approved these changes

2022-12-06 17:39 UTC, merged