Release notes 2022.2
pymor/pymor pull request #1828
Opened 2022-12-12 18:05 UTC by pmli

2022-12-13 14:47 UTC, artpelling requested changes

2022-12-13 14:47 UTC, artpelling commented on docs/source/release_notes/2022.2.rst
> +approximation of |TransferFunctions|. The |PAAAReductor| can handle any models
```suggestion
approximation of |TransferFunctions|. The :class:`PAAARedcutor <pymor.reductors.aaa.PAAAReductor` can handle any models
```

2022-12-13 14:47 UTC, artpelling commented on docs/source/release_notes/2022.2.rst
> +this release we are adding the parametric version of the algorithm
```suggestion
this release, we are adding the parametric version of the algorithm
```

2022-12-13 14:47 UTC, artpelling commented on docs/source/release_notes/2022.2.rst
> +only compute the standard, Lyapunov Gramians.
```suggestion
only compute the standard Lyapunov Gramians.
```

2022-12-15 17:06 UTC, sdrave commented
@TiKeil, can you add a few lines regarding the DWR stuff.

2022-12-16 15:12 UTC, sdrave approved these changes
Fine from my side.

Depending on whether or not the impulse response PR makes it into the release or not, the respective part of the release notes has to be adapted. Also, the release date still needs to be specified.

2022-12-16 17:52 UTC, artpelling approved these changes

2022-12-16 18:06 UTC, merged