Update and extend release checklist
pymor/pymor pull request #1911
Opened 2023-01-10 08:57 UTC by HenKlei

2023-01-10 09:00 UTC, HenKlei commented
Maybe some comments/details on sdist and how the distribution to pypi works would be nice.

2023-01-10 09:40 UTC, HenKlei commented
Thanks @renefritze, I addressed all your points. Maybe you can take another short look?

2023-01-10 09:48 UTC, renefritze approved these changes
Very nice. Thanks. We should still wait for someone that's not me to have look though :)

2023-01-10 14:10 UTC, pmli requested changes

2023-01-10 14:10 UTC, pmli commented on docs/RELEASE_CHECKLIST.md
> +        to the `RELEASE_TAG`.)
```suggestion
 1. [ ] Create a release branch in `pymor/pymor`. Should have a `.x` as the last part of the branch name in contrast
        to the `RELEASE_TAG`.
```

2023-01-10 14:10 UTC, pmli commented on docs/RELEASE_CHECKLIST.md
> + 1. [ ] Produce sdist with checked out tag `RELEASE_TAG`, make sure sdist version is correct.
```suggestion
 1. [ ] Run `python setup.py sdist` (on checked out tag `RELEASE_TAG`) and check that it produces `dist/pymor-RELEASE_TAG.tar.gz`.
```

2023-01-10 14:10 UTC, pmli commented on docs/RELEASE_CHECKLIST.md
> +```
```suggestion

       ```bash
       source pymor/pymor/.env
       cd pymor/docker
       git checkout "${CI_IMAGE_TAG}"
       git tag -a RELEASE_TAG -m RELEASE_TAG
       ```
```

2023-01-10 14:10 UTC, pmli commented on docs/RELEASE_CHECKLIST.md
> + 1. [ ] Wait for CI build to finish in `pymor/pymor`. The tagged commit will be deployed to pypi automatically,
```suggestion
 1. [ ] Wait for CI build to finish in `pymor/pymor`. The tagged commit will be deployed to PyPI automatically,
```

2023-01-10 14:21 UTC, HenKlei commented on docs/RELEASE_CHECKLIST.md
> + 1. [ ] Produce sdist with checked out tag `RELEASE_TAG`, make sure sdist version is correct.
```suggestion
 1. [ ] Run `python setup.py sdist` (on checked out tag `RELEASE_TAG`) and check that it
        produces `dist/pymor-RELEASE_TAG.tar.gz`.
```

2023-01-10 14:24 UTC, HenKlei commented
Thanks @pmli for the nice improvements. From my side this is good to go now, what do you think @pmli?

2023-01-10 18:19 UTC, pmli requested changes
Just one minor thing, otherwise looks good to me.

2023-01-10 18:19 UTC, pmli commented on docs/RELEASE_CHECKLIST.md
> + 1. [ ] Bump/create demo docker, i.e. in `pymor/docker` go to the `demo`-folder and copy the subfolder of the last
```suggestion
 1. [ ] Bump/create demo docker, i.e., in `pymor/docker` go to the `demo` folder and copy the subfolder of the last
```

2023-01-10 18:20 UTC, pmli commented
Thanks for working on this @HenKlei.

2023-01-11 14:27 UTC, pmli approved these changes

2023-01-11 14:27 UTC, merged