Remove name inheritance in `project`
pymor/pymor pull request #1986
Opened 2023-03-15 19:13 UTC by pmli

Closes #1971.

2023-03-22 09:34 UTC, sdrave reviewed
In `operators.constructions` are several similar cases, where the constructed operator gets a suffix. I think we should either remove these cases as well, or opt for a `_projected` suffix here as well. 

With the goal of making pyMOR code easier to write, it might make sense to drop the name handling everywhere. But I'm not sure if we would loose information that is useful in some places. As discussed before, I'd like to replace names with a semantically more powerful mechanism, but I'm still not sure how this will look like and when it will be ready, so we should not count on it too much.

@pymor/all, any opinions?

`names` are also handled in `reductors.neural_network`, `reductors.sobt` and `reductors.symplectic`.

2023-04-15 19:55 UTC, ftschindler commented
Just pointing out [something we stumbled upon in LincombOperators](https://github.com/pymor/pymor/discussions/1575#discussioncomment-2196917), without a clear idea if/how this relates.

2023-04-27 18:11 UTC, pmli commented
We decided to postpone the discussion about removing `names` and just add the `_projected` suffix.

2023-05-16 18:58 UTC, pmli commented on src/pymor/algorithms/projection.py
> +        return op.name + '_projected'
@sdrave What do you think about this approach?

2023-06-07 07:19 UTC, sdrave requested changes
Generally, I'd be ok with the approach. However, if projected operators get a new name with a `_projected` suffix, then this should be the case for all operators. So also `LincombOperator` etc. should be handled.

If you come to the conclusion that this is too much of a hassle, then we can also go with completely getting rid of name inheritance for projected operators: Thinking about it, I don't believe that there are relevant cases where names are that useful after projection. Regarding the handling of `LincombOperators` under addition: Firstly, again, I think it's not really relevant after projection. Secondly, maybe that feature is too surprising anyway, and `+`, etc. should always merge `LincombOperators`. You could still manually instantiate a `LincombOperator` if you want to preserve structure.)

Now that I have written this, I think I'd actually prefer the second option. But I leave it up to you, @pmli.

2023-06-14 12:16 UTC, sdrave requested changes
In cases where `with_` is used, one would need to add `name=None` to ensure that names are not inherited. This is the case for `action_LincombOperator` and `action_SelectionOperator`. Also, some rules in `project_to_subbasis` are affected.

2023-06-14 12:16 UTC, sdrave commented on src/pymor/algorithms/projection.py
> +                                                      self._add_suffix(op))
```suggestion
                                                      projected_collateral_basis, op.triangular, None)
```

2023-06-21 11:23 UTC, pmli commented
> Also, some rules in `project_to_subbasis` are affected.

I guess it is ok if `project_to_subbasis` preserves the name, since the operator was already projected?

2023-06-21 12:30 UTC, sdrave requested changes
> > Also, some rules in `project_to_subbasis` are affected.
> 
> I guess it is ok if `project_to_subbasis` preserves the name, since the operator was already projected?

Maybe. But the current implementation seems to be inconsistent. Some operators preserve their names, others don't. I dislike that. A quick solution might be to add an `.with_(name=None)` to what the rule table returns. Same could be done for `project`.

2023-06-28 13:19 UTC, pmli commented
> A quick solution might be to add an `.with_(name=None)` to what the rule table returns. Same could be done for `project`.

Sounds like a good idea to me. I just had to make some adjustments (add names to block `Operators` and `ProjectedOperator`, and check in `project` if the bases are `None` to avoid creating a new `Operator`).

2023-06-28 13:52 UTC, sdrave approved these changes
Looks good!

2023-06-28 19:38 UTC, merged