Mu algebra
pymor/pymor pull request #2004
Opened 2023-04-01 11:44 UTC by peoe

2023-04-04 15:25 UTC, pmli commented on src/pymor/parameters/base.py
> +        return Mu({key: -self[key] for key in self.keys()})
```suggestion
        return Mu({key: -value for key, value in self.items()})
```

2023-04-04 15:25 UTC, pmli commented on src/pymor/parameters/base.py
> +        return self - other
```suggestion
        return -self + other
```

2023-04-04 15:25 UTC, pmli commented on src/pymor/parameters/base.py
> +        return Mu({key: self[key] + other[key] for key in self.keys()})
```suggestion
        return Mu({key: self[key] + other[key] for key in self})
```

2023-04-04 15:25 UTC, pmli commented on src/pymor/parameters/base.py
> +        return Mu({key: self[key] * other for key in self.keys()})
```suggestion
        return Mu({key: self[key] * other for key in self})
```

2023-05-16 19:05 UTC, pmli commented on src/pymortests/parameters/parameters.py
> +    assert all((mu - other).to_numpy() == (mu_np - other_np))
Should also test the version with `other - mu`.

2023-06-07 07:02 UTC, sdrave requested changes
Apart from my single remark, this is good to go!

@peoe, please add an entry to `AUTHORS.md` if you like.

2023-06-07 07:02 UTC, sdrave commented on src/pymor/parameters/base.py
> +                raise NotImplementedError
I'm not sure what you are trying to achieve by catching exceptions here. `NotImplementedError` suggests that there could be an implementation, but I don't see how. Also, catching an arbitrary `Exception` is considered bad practice. Overall, I'd just go with:

```suggestion
            other = self.parameters.parse(other)
```

2023-06-14 12:08 UTC, sdrave approved these changes

2023-06-14 13:06 UTC, merged