Cast VectorSpace dimensions as integers
pymor/pymor pull request #2063
Opened 2023-05-28 13:44 UTC by peoe

This PR proposes #2062.

I'm a bit torn about his implementation because most `VectorSpace`s use slightly different methods to compute their dimension. If you have ideas on how to unify these, please let me know.

2023-06-10 11:05 UTC, peoe commented
@pmli : Does this better suit the "don't hide issues" mentatlity? This way, the setter handles type checking and I also got rid of additional getter implementations.

2023-06-11 20:38 UTC, pmli reviewed
The trick with the setter looks very good. I added a comment about type-checking.

2023-06-11 20:38 UTC, pmli commented on src/pymor/vectorarrays/interface.py
> +        if not isinstance(dim, int):
This fails on NumPy integers:

```python
>>> import numpy as np
>>> a = np.int32(5)
>>> a
5
>>> isinstance(a, int)
False
```

Using `numbers.Integral` makes it work:

```python
>>> from numbers import Integral
>>> isinstance(a, Integral)
True
```

Still, that doesn't work with 0-dimensional NumPy arrays, where checking the dimension and dtype seems to be necessary:

```python
>>> b = np.array(5)
>>> b
array(5)
>>> print(b)
5
>>> isinstance(b, Integral)
False
>>> b.ndim == 0 and np.issubdtype(b.dtype, np.integer)
True
```

I'm not sure how far we need to go. Maybe it's ok to just limit to the `Integral` check and see if issues come up.

2023-06-14 12:28 UTC, sdrave requested changes
Apart from my comments, I feel that this approach is unnecessarily fancy. I'd just check the argument in `NumpyVectorSpace.__init__`. Most spaces derive there dimension from other data anyway.

2023-06-14 12:28 UTC, sdrave commented on src/pymor/vectorarrays/interface.py
> +        self._dim = dim
I'm not quite sure, but doesn't this make the dimension of a `VectorSpace` mutable? This should not be allowed ..

2023-06-14 12:28 UTC, sdrave commented on src/pymor/bindings/fenics.py
> +        self.dim = df.Function(self.V).vector().size()
This means that creating a new `FenicsVectorSpace` always entails creating a new `Function` object and, thus, allocating memory for a DOF vector that is never used. I generally assume that creating a `VectorSpace` is cheap.
Note that there are very few places in pyMOR where the dimension of a `VectorSpace` actually is relevant.

(The current code is not optimal either, of course. The dimension should be cached.)

2023-06-29 19:49 UTC, sdrave commented
Closing in favor of #2081.

2023-06-29 19:49 UTC, closed without merging