Self-documenting help target for Makefile
pymor/pymor pull request #2179
Opened 2023-09-12 14:43 UTC by peoe

This PR proposes a default `help` target as mentioned in issue #2097. This target is self-documenting in the sense that any targets can be included in the generated help message by documenting it as follows:

```make
<target>: [dependencies] ## Target documentation
```

I've added basic docstrings for the targets where I could easily infer that they needed documentation and what their intended effects are, but this leaves out a number of other targets. Before converting this to a full PR, I would like some feedback on which targets still need documentation, as well as how to improve the current documentation.

Furthermore, I would like some feedback with regards to the formatting of the individual lines. Is some more spacing necessary? Should it include colour?

2023-09-25 09:12 UTC, sdrave requested changes

2023-09-25 09:12 UTC, sdrave commented on Makefile
> +ci_requirements: ci_current_requirements ci_oldest_requirements ci_fenics_requirements ci_conda_requirements ## run the Docker CI images
This builds the requirements-*.txt files ..

2023-09-25 09:12 UTC, sdrave commented on Makefile
>  ci_current_image_run:
These targets run the ci images ...

2023-09-26 20:31 UTC, pmli commented on Makefile
> +default: help
I guess this can be removed.

2023-09-26 20:31 UTC, pmli commented on Makefile
> +README: README.html ## generate the README for the docs
```suggestion
README: README.html ## convert README.md to other formats
```

2023-09-26 20:31 UTC, pmli commented on Makefile
>  README.html: README.md
```suggestion
README.html: README.md ## convert README.md to HTML format
```

2023-11-06 20:33 UTC, pmli approved these changes

2023-11-09 10:31 UTC, sdrave approved these changes
Thanks!

@peoe, do you want to make an entry in `AUTHORS.md`?

2023-11-15 11:37 UTC, merged