TR description in optimization tutorial
pymor/pymor pull request #2181
Opened 2023-09-18 13:08 UTC by peoe

This PR proposes an addition to the optimization tutorial in order to describe the usage of the trust-region algorithm and parts of the underlying theory.

I'd be glad to get some feedback on the clarity of the wording, especially the distinction of the inner/outer loop mechanic because this is essential for the algorithm.

2023-09-19 19:52 UTC, TiKeil submitted a review, later dismissed
Hi Peter,

thanks for including the TR methods in the tutorial. I think the section is well written and the wording was already quite good. I added some comments that you could commit if you want.
These are mostly just suggestions.

Two major comments:

1. The methods `opt_along_path` and `opt_along_path_adaptively` were basically in the tutorial since we did not have the TR method, yet. The TR method can be seen as the certified replacement of the other methods. I think it is a little bit dangerous to sell these two methods before the TR method as they were simply invented for presentational reasons and are rather hacked inside the tutorial, not using any pyMOR algorithm. Thus, I would suggest removing these two methods entirely and only concentrating on the TR method.
2. I know that it is a little bit more work, but I think it would be really great if we could get rid of the 'scipy.optimize.minimize' method entirely.

I do not remember but do we use the same problem as in the TR demo for the tutorial?

Thank you.

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +respect to the underlying error estimator.
Although this is true for the TR method, it is also already true for the method that has been discussed in the former section. I would rather tend to remove the former method and maybe even the one before (see the main comment of the review).

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +In the trust-region method, we replace the global problem with local surrogates,
```suggestion
In the trust-region method, we iteratively replace the global problem with local surrogates,
```

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +when we either are close to the border of the trust-region or when the model confidence
```suggestion
when we either are close to the boundary of the trust-region or when the model confidence
```

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +In effect, this creates two loops: the outer iterates over global parameter space and
```suggestion
Thus, the TR consists of one outer loop and many inner loops. The outer loop iterates over global parameter space and
```

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +inner solves the local problems with BFGS.
```suggestion
inner loops use a modified version of the projected BFGS to solve the local problems.
```

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +{math}`J_r`, this approach takes the shape
```suggestion
{math}`J_r`, the local problems can be written as
```

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +open balls of radius {math}`\tau`, however the typical estimators in this tutorial's
```suggestion
open balls of radius {math}`\tau`, however using model reduction estimators as in this tutorial's
```

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +setting create much more complex shapes.
```suggestion
setting creates much more complex shapes.
```

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +If a local optimization in the inner loop fails, we retry the surrogate problem with a
```suggestion
If a local optimization in an inner loop fails, we retry the surrogate problem with a
```

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +smaller trust-region, thus limiting the use of the current model.
```suggestion
smaller trust-region, thus limiting the trustworthiness of the current model.
```

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +reasonable assumption that the globally optimal parameter is outside of the current region,
```suggestion
reasonable assumption that the globally optimal parameter is outside of the current trust-region and thus we stop the inner iteration.
```

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +inner optimization problem.
I do not understand this sentence, to be honest. Do you mean that we enlarge the radius by enrichment or you mean the delta that can be enlarged for the next inner loop?

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +Again, we only need {math}`4` enrichments and ended up with an approximation
```suggestion
Again, we only need {math}`4` enrichments and end up with an approximation
```

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +enrichment described above.
```suggestion
enrichment described above.

The above-described algorithm can be executed as follows.
```

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +the overhead of ROM evaluations and line searches performed in the BFGS step.
This again suggests that we should not stick with the former methods as they heavily depend on the tolerances and a certified method should anyway be much more preferred to be used.

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +To conclude, we once again compare all methods that we have discussed in this notebook.
In this case, only the report for the TR method is shown?

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
I guess this part needs to be updated. see above.

2023-09-19 19:52 UTC, TiKeil commented on docs/source/tutorial_optimization.md
> +
I think we are lacking a bit more interpretation of the results.

2023-09-26 16:05 UTC, peoe commented
Thanks for the extensive review @TiKeil ! For now I have implemented the first part of your recommendations, I'll try and get around to the second part tomorrow.

As far as I can tell, the optimization tutorial uses the problem from the `linear_optimization.py` demo -- which we simply import in the `trust_region.py` demo.

2023-09-27 07:52 UTC, sdrave commented
> As far as I can tell, the optimization tutorial uses the problem from the linear_optimization.py demo -- which we simply import in the trust_region.py demo.

We now have `pymor.models.examples` where such models can be placed into. At least if they are interesting enough.

2023-11-14 13:10 UTC, sdrave commented
@peoe, @TiKeil, how should we proceed with this PR? I think this need to come to a conclusion. If need be, I can try to do it, but I'm not sure if I'm the best person for the job.

2023-11-14 17:48 UTC, TiKeil commented
Is there something to decide upon or is it "just" working on finalizing the PR ?

2023-11-17 22:12 UTC, sdrave commented
> Is there something to decide upon or is it "just" working on finalizing the PR ?

I think it's just finalizing the tutorial.

2023-11-23 10:54 UTC, sdrave commented
@TiKeil, hard freeze for the next release is in one week. Do you think you find time to take a look at this until then?

2023-11-26 19:23 UTC, TiKeil commented
I'm afraid I will not be able to work on this before the freeze.
But I will look at it asap.

2023-11-27 10:07 UTC, sdrave commented
> I'm afraid I will not be able to work on this before the freeze. But I will look at it asap.

Ok, I'll remove the release milestone for now. Release is planned for December 7. As this is only documentation related, it might still get in after hard freeze ..

2024-03-14 08:58 UTC, sdrave commented
@TiKeil, did you have a chance to look at this PR? Soft freeze for the next release would be May 31 ..

2024-06-06 13:23 UTC, sdrave commented
@HenKlei, maybe you might want to take over. Should not be too much work to finalize this, I hope.

2024-06-06 14:12 UTC, HenKlei commented
> @HenKlei, maybe you might want to take over. Should not be too much work to finalize this, I hope.

Yes, I can take over here. Since the last discussions on this PR were already a long time ago, I do not really remember the status of the PR. Do you have immediate things to adjust/change in mind, @sdrave?

2024-06-21 12:57 UTC, sdrave requested changes

2024-06-21 12:57 UTC, sdrave commented on docs/source/tutorial_optimization.md
> +trust-region with tolerance {math}`\tau > 0` for an error estimator {math}`e_r` of our choice
```suggestion
trust-region with tolerance {math}`\tau > 0` for an error estimator {math}`e_r` of our choice,
```

2024-06-21 12:57 UTC, sdrave commented on docs/source/tutorial_optimization.md
> +reduction in this tutorial's setting creates much more complex shapes.
```suggestion
correspond to open balls of radius {math}`\tau`. However, using model reduction error estimators as in this tutorial, creates much more complex shapes.
```

2024-06-21 12:57 UTC, sdrave commented on docs/source/tutorial_optimization.md
> +:width: 100%
That's too wide. See rendered output.

2024-06-21 12:57 UTC, sdrave commented on docs/source/tutorial_optimization.md
> +and thus we stop the inner iteration. After computing an inner solution we then have the
```suggestion
and, thus, we stop the inner iteration. After computing an inner solution we then have the
```

2024-06-21 12:57 UTC, sdrave commented on docs/source/tutorial_optimization.md
> +by estimating if the current surrogate is trustworthy enough to increase the trust-radius
```suggestion
by estimating whether the current surrogate is trustworthy enough to increase the trust-radius
```

2024-06-21 12:57 UTC, sdrave commented on docs/source/tutorial_optimization.md
> +and only enrich the model if the estimated quality is no longer sufficient.
```suggestion
and only enriching the model if the estimated quality is no longer sufficient.
```

2024-06-21 12:57 UTC, sdrave commented on docs/source/tutorial_optimization.md
> +previous methods. Unfortunately, the trust-region method takes longer because of
In the rendered documentation, the TR algorithm is the fastest. Otherwise, this should be phrased more positively.

2024-06-21 12:57 UTC, sdrave commented on docs/source/tutorial_optimization.md
> +It is apparent that for this example no drastic changes occur when using the different
So we don't need real gradients in the first place? When can we expect to need them?

2024-06-21 12:57 UTC, sdrave commented on docs/source/tutorial_optimization.md
> +It is expected that the for problems of larger scale the speedup is even more pronounced.
'expected' -> we are unsure?

2024-06-21 12:57 UTC, sdrave commented on docs/source/tutorial_optimization.md
>  Moreover, we focused on the lack of overall efficiency of standard RB methods.
We haven't really seen that global RB methods are not competitive.

2024-06-21 12:57 UTC, sdrave commented on docs/source/tutorial_optimization.md
>  In this tutorial we have only covered a few basic approaches to combine model
I wouldn't call the TR-algorithm basic.

2024-06-21 12:57 UTC, sdrave commented on docs/source/tutorial_optimization.md
> +We have therefore seen a way to efficiently use local surrogate models in a trust-region
'we have seen a way' sounds very strange.

2024-06-21 13:25 UTC, HenKlei commented
Thanks @sdrave for taking a look. I tried to address all your comments.

2024-06-24 11:58 UTC, sdrave approved these changes

2024-06-24 11:58 UTC, sdrave commented on docs/source/tutorial_optimization.md
> +In this tutorial we have only covered a few approaches to combine model
```suggestion
We have only covered a few approaches to combine model
```
Previous paragraph already starts with 'In this tutorial'.

2024-06-24 11:58 UTC, sdrave commented on docs/source/tutorial_optimization.md
> +[KMSOV20](<https://www.esaim-m2an.org/articles/m2an/abs/2021/04/m2an200123/m2an200123.html>)
```suggestion
[KMSOV20](<https://www.esaim-m2an.org/articles/m2an/abs/2021/04/m2an200123/m2an200123.html>),
```

2024-06-24 15:16 UTC, sdrave commented
Precommit is still complaining, @HenKlei.

2024-06-25 12:18 UTC, merged