Recalculated shifted Cholesky QR
pymor/pymor pull request #2304
Opened 2024-07-29 14:31 UTC by maxbindhak

Shifted Cholesky QR version, in which the shift gets recalculated in every iteration again. Seem to work reliable even for highly ill-conditioned matrices. Requires possibly far more iterations (e.g. `maxIter=10`) in some cases.

See discussion in #2301

2024-08-01 15:17 UTC, sdrave commented
Minor remark: if we are going to support shift-recalculation, we should either always do it, or offer it as an option to `shifted_chol_qr`. In either case, we need to ensure that

2024-11-08 08:39 UTC, HenKlei commented
Any progress on this @maxbindhak? Who feels responsible to look into this @pymor/main?

2024-12-06 07:16 UTC, sdrave requested changes
Code looks good, except for the issue with `ListVectorArray`. If I'm not mistaken, this cannot work for `ListVectorArrays` with non-zero offset?

Also, there don't seem to be any test for the `offset > 0` case. Could you add one?

2024-12-06 07:16 UTC, sdrave commented on src/pymor/algorithms/chol_qr.py
> +            X = A.gramian(product)
Shouldn't this be

```suggestion
            X = A[offset:].gramian(product)
```

2024-12-10 15:40 UTC, sdrave approved these changes

2024-12-10 15:41 UTC, sdrave commented
Thanks, looks good now!

2024-12-10 16:27 UTC, merged