Remove space ids
pymor/pymor pull request #2357
Opened 2024-09-19 15:21 UTC by sdrave

2024-09-23 08:11 UTC, HenKlei approved these changes

2024-09-23 12:14 UTC, pmli requested changes
Files `reduced_model.out` and `results.out` have been added. I guess this was not on purpose. I had similar issues with those files, perhaps they could be added to `.gitignore`.

2024-09-24 08:28 UTC, sdrave commented
> Files `reduced_model.out` and `results.out` have been added. I guess this was not on purpose. I had similar issues with those files, perhaps they could be added to `.gitignore`.

Ouch. They were actually listed in `.gitignore`, but only for specific paths. I have changed that.

2024-09-24 11:55 UTC, pmli requested changes
Looks good to me, except that `DuneXTMatrixOperator` documents `source_id` and `range_id`.

2024-09-24 11:55 UTC, pmli commented on .gitignore
> +results.out
Two lines could be removed now.

2024-09-25 08:50 UTC, sdrave commented on .gitignore
> +results.out
Done.

2024-09-25 12:37 UTC, pmli approved these changes

2024-09-26 13:41 UTC, merged