Time stepping backwards in time
pymor/pymor pull request #2378
Opened 2024-10-28 14:02 UTC by HenKlei

Resolves #2310.

2024-10-29 08:27 UTC, sdrave reviewed
Just wondering: Do we want this on the level of TimeSteppers? One could also consider having a `MuMappedOperator`, which applies some tranformation to `mu` before passing it to the wrapped operator (like mapping `t` to `T-t`). Then `compute` could wrap the `Operator` and `RHS` before passing it to the timestepper. (Or this could happen in the `TimeStepper` interface methods.) Not sure about the advantages/disadvantages.

2024-10-29 08:35 UTC, HenKlei commented
> Just wondering: Do we want this on the level of TimeSteppers? One could also consider having a `MuMappedOperator`, which applies some tranformation to `mu` before passing it to the wrapped operator (like mapping `t` to `T-t`). Then `compute` could wrap the `Operator` and `RHS` before passing it to the timestepper. (Or this could happen in the `TimeStepper` interface methods.) Not sure about the advantages/disadvantages.

Could be an option as well. But would that actually be enough? Assume the operator is independent of time. If I understand your suggestion correctly, the backward time stepping would behave exactly like the forward time stepping, right? Or do I miss anything here?

2024-10-29 09:36 UTC, sdrave commented
> > Just wondering: Do we want this on the level of TimeSteppers? One could also consider having a `MuMappedOperator`, which applies some tranformation to `mu` before passing it to the wrapped operator (like mapping `t` to `T-t`). Then `compute` could wrap the `Operator` and `RHS` before passing it to the timestepper. (Or this could happen in the `TimeStepper` interface methods.) Not sure about the advantages/disadvantages.
> 
> Could be an option as well. But would that actually be enough? Assume the operator is independent of time. If I understand your suggestion correctly, the backward time stepping would behave exactly like the forward time stepping, right? Or do I miss anything here?

I'm thinking about something like

```python
class TimeReversedOperator(Operator):
    def __init__(self, T, op):
        ...
    def apply(self, U, mu):
        mu = mu.with_(t = self.T - mu['t'])
        return self.op.apply(U, mu=mu)
```

Yes, if neither operator nor rhs would depend on time, this would be the same as forward time stepping. Should it be different?

2024-11-08 08:51 UTC, HenKlei commented
@HenKlei make sure to finish this...

2024-12-05 14:47 UTC, HenKlei commented
Ping @sdrave

2024-12-05 15:31 UTC, sdrave requested changes
Looks good to me. I have only minor stylistic suggestions. What is missing though is some documentation that `final_time` can also be smaller than `initial_time` and what this means.

2024-12-05 15:31 UTC, sdrave commented on src/pymor/algorithms/timestepping.py
> +            sign = -1
```suggestion
        sign = np.sign(end_time - initial_time)
```

2024-12-05 15:31 UTC, sdrave commented on src/pymor/algorithms/timestepping.py
> +            sign = -1
```suggestion
        sign = np.sign(end_time - initial_time)
```

2024-12-05 15:31 UTC, sdrave commented on src/pymor/algorithms/timestepping.py
> +            sign = -1
```suggestion
        sign = np.sign(end_time - initial_time)
```

2024-12-05 18:52 UTC, HenKlei commented
> Looks good to me. I have only minor stylistic suggestions. What is missing though is some documentation that `final_time` can also be smaller than `initial_time` and what this means.

Thanks for taking another look. I added a brief explanation, would that be enough?

2024-12-05 22:02 UTC, sdrave commented
> > Looks good to me. I have only minor stylistic suggestions. What is missing though is some documentation that `final_time` can also be smaller than `initial_time` and what this means.
> 
> Thanks for taking another look. I added a brief explanation, would that be enough?

I'm not sure if it's mathematically clear what 'backwards time stepping' means. Maybe one should rather write that the corresponding terminal-value problem is solved?

2024-12-06 08:04 UTC, HenKlei commented
> I'm not sure if it's mathematically clear what 'backwards time stepping' means. Maybe one should rather write that the corresponding terminal-value problem is solved?

You are right. I am still not sure if the new formulation is better.
And while changing the documentation, I was wondering whether one should actually change the order of the result. If one thinks of backwards time stepping the current order makes sense, however, if one sees it as a terminal value problem, the order should be reversed.

2024-12-06 09:09 UTC, sdrave commented
> > I'm not sure if it's mathematically clear what 'backwards time stepping' means. Maybe one should rather write that the corresponding terminal-value problem is solved?
> 
> You are right. I am still not sure if the new formulation is better. And while changing the documentation, I was wondering whether one should actually change the order of the result. If one thinks of backwards time stepping the current order makes sense, however, if one sees it as a terminal value problem, the order should be reversed.

I like the 'terminal-value problem' formulation because at least it is a well-defined mathematical problem, and I think it makes more sense to speak about the problem to be solved than what a particular implementation might do.

Regarding the ordering: I guess the problem is that we use `initial_time` for the terminal value. If you think about it being the terminal value, the corresponding vector should be last in the array. As a user of the interface reading `initial_time`, I would expect the value to go first. My feeling is that keeping the current convention would be best.

2024-12-06 09:10 UTC, sdrave approved these changes

2024-12-06 09:26 UTC, HenKlei commented
> > > I'm not sure if it's mathematically clear what 'backwards time stepping' means. Maybe one should rather write that the corresponding terminal-value problem is solved?
> > 
> > 
> > You are right. I am still not sure if the new formulation is better. And while changing the documentation, I was wondering whether one should actually change the order of the result. If one thinks of backwards time stepping the current order makes sense, however, if one sees it as a terminal value problem, the order should be reversed.
> 
> I like the 'terminal-value problem' formulation because at least it is a well-defined mathematical problem, and I think it makes more sense to speak about the problem to be solved than what a particular implementation might do.
> 
> Regarding the ordering: I guess the problem is that we use `initial_time` for the terminal value. If you think about it being the terminal value, the corresponding vector should be last in the array. As a user of the interface reading `initial_time`, I would expect the value to go first. My feeling is that keeping the current convention would be best.

Totally agreed! Thanks for clarifying this!

2024-12-06 10:23 UTC, merged